name: Build and package RoBERTa-sequencing to Dockerhub

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Authenticate with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: set auto-install of extensions
      run: |
        az upgrade
        az extension add -n ml
        az config set extension.use_dynamic_install=yes_without_prompt
    
    #- name: attach workspace
    #  run: az ml folder attach -w "pmlops" -g "skinnerexp-rg"
    
    - name: retrieve the model
      run: az ml model download --name roberta-sequence --version 1 -wworkspace-name pmlops
    
    - name: auth to docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: build flask-app container
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_REPO }}:latest
  
